project/apps/Clientes/urls.py
from django.urls import path

from .views import crear_cliente, home #busqueda

app_name = "Clientes"

urlpatterns = [
    path("", home, name="home"),
    path('crear/', crear_cliente, name="crear"),
    #path('busqueda/', busqueda, name="busqueda")
]

project/apps/Home/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path('login/', views.login_request, name="login"),
    path('logout/', LogoutView.as_view(template_name="Home/logout.html"), name="logout"),
    path('about/', TemplateView.as_view(template_name="Home/about.html"), name="about"),
    path('register/', views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()

project/apps/Seguros/urls.py
from django.urls import path

from . import views

app_name = "Seguros"

urlpatterns = [path("", views.index, name="home")]

# SEGUROCATEGORIA
urlpatterns += [
    path("seguroscategoria/list/", views.SegurosCategoriaList.as_view(), name="seguroscategoria_list"),
    path("seguroscategoria/create/", views.SegurosCategoriaCreate.as_view(), name="seguroscategoria_create"),
    path("seguroscategoria/detail/<int:pk>", views.SegurosCategoriaDetail.as_view(), name="seguroscategoria_detail"),
    path("seguroscategoria/update/<int:pk>", views.SegurosCategoriaUpdate.as_view(), name="seguroscategoria_update"),
    path("seguroscategoria/delete/<int:pk>", views.SegurosCategoriaDelete.as_view(), name="seguroscategoria_delete"),
]

# SEGURO
urlpatterns += [
    path("seguros/list/", views.SegurosList.as_view(), name="seguros_list"),
    path("seguros/create/", views.SegurosCreate.as_view(), name="seguros_create"),
    path("seguros/detail/<int:pk>", views.SegurosDetail.as_view(), name="seguros_detail"),
    path("seguros/update/<int:pk>", views.SegurosUpdate.as_view(), name="seguros_update"),
    path("seguros/delete/<int:pk>", views.SegurosDelete.as_view(), name="seguros_delete"),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls")),
    path("Clientes/", include("Clientes.urls")),
    path("Seguros/", include("Seguros.urls")),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/Home/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        # Quita los mensajes de ayuda
        # help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/apps/Home/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http.request import HttpRequest
from django.shortcuts import render

from . import forms


def home(request):
    return render(request, "Home/index.html")

# Login
def login_request(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password")
            user = authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request, "Home/index.html", {"mensaje": "Sesión Iniciada"})
    else:
        form = forms.CustomAuthenticationForm()
    return render(request, "Home/login.html", {"form": form})

# @staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "Home/index.html", {"mensaje": "Registro Exitoso"})
    else:
        form = forms.CustomUserCreationForm()
    return render(request, "Home/register.html", {"form": form})

project/apps/Home/templates/Home/about.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
Quienes somos
{% endblock %}

{% block INDEX_CONTENIDO %}
    <div class="text-center display-1 mb-5 mt-3">
        
        Somos un grupo de jóvenes abogados que trabajamos en el mercado de seguros desde hace varios años en el cual notamos un “espacio vacío” entre las aseguradoras y sus clientes debido principalmente al engorroso lenguaje legal. Los contratos de seguros con sus condiciones generales, especiales y particulares, endosos, anexos y sin fin de referencias circulares a las cláusulas de las cláusulas vuelven la experiencia de comprar una cobertura algo muy tedioso y complicado.

        En ese contexto, nace Urano Broker de Seguros para acompañar a las empresas y a los seres humanos que las integran a gestionar sus riesgos patrimoniales y a adquirir los seguros que necesiten de una manera más amigable y enriquecedora para sus vidas.

    </div>
{% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Urano - Broker de Seguros</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'Home/assets/logo_avatar.svg' %}  " />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->

        {% include 'Home/navbar.html' %}

        <!-- Page Content-->
        <div class="container px-4 px-lg-5">

            {% block BASE_CONTENIDO %}


            {% endblock BASE_CONTENIDO %}

        </div>
        <!-- Footer-->
        {% include 'Home/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Home/js/scripts.js' %} "></script>
    </body>
</html>

project/apps/Home/templates/Home/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ card }} {{ saludo }}</h2>
            </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">cotizar</a></div>
    </div>
</div>

project/apps/Home/templates/Home/footer.html
<footer class="bg-dark fixed-bottom ">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright Urano Broker de Seguros</p></div>
</footer>

project/apps/Home/templates/Home/index.html
{% extends 'Home/base.html' %}
{% load static %}

{% block BASE_CONTENIDO %}


    {% block INDEX_CONTENIDO %}

    
        {% if user.is_authenticated %}
            {{ mensaje }}
            <h3> Bienvenido a Urano {{ user.username }}</h3>
        {% endif %}

        {% if user.is_staff %}
            <div class="row">
                <a href="{% url 'admin:index' %}" class="btn btn-outline-dark">Panel de Administración</a>
            </div>
            <div class="row">
                <a href="{% url 'Home:register' %}" class="btn btn-outline-dark">Registro de Usuarios</a>
            </div>
        {% endif %}


        <!-- Heading Row-->
        <div class="row gx-4 gx-lg-5 align-items-center my-5">
            <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'Home/img/urano_logo.svg' %}" alt="..." /></div>
            <div class="col-lg-5">
            <h1 class="font-weight-light">Seguros para empresas</h1>
               
                <p>Nuestro objetivo es acercar a las pequeñas y medianas empresas los beneficios de contar con un plan de cobertura y mitigación de riesgo accesible a su realidad jurídica y económica, en compañías de probada solidez financiera. </p>
               
               
                <a class="btn btn-primary" href="https://wa.me/5491139305487" target="_blank">WhatsApp</a>
            </div>
        </div>

        <!-- Content Row-->
        <div class="row gx-4 gx-lg-5">

            {% include 'Home/card.html' with card="Riesgos Materiales" %}
            {% include 'Home/card.html' with card="Riesgos Legales" %}
            {% include 'Home/card.html' with card="Riesgos Cibernéticos" %}
        
            

        </div>
    {% endblock INDEX_CONTENIDO %}

{% endblock BASE_CONTENIDO %}

project/apps/Home/templates/Home/index_back.html
<div class="d-grid gap-3 "> 
    <a href="{% url 'Home:home' %}" class="btn btn-info">Ir al menú principal</a>
</div>

project/apps/Home/templates/Home/login.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
Login
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-3"> 
            <button type="submit" class="btn btn-success">Sign in</button>
        </div>
    </form>

{% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/logout.html
{% extends 'Home/index.html' %}

{% block INDEX_CONTENIDO %}
    <div class="fs-3 fst-italic ">
        <p>Sesión finalizada</p>
    </div>
{% endblock %}

project/apps/Home/templates/Home/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Urano - Broker de Seguros</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'Home:home' %}">Inicio</a></li>
                
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link " href="{% url 'Clientes:home' %}">Clientes</a></li>
                    <li class="nav-item"><a class="nav-link " href="{% url 'Seguros:home' %}">Seguros</a></li>
                    <li class="nav-item"><a class="nav-link text-bg-info">{{ user.username }}</a></li>
                    <li class="nav-item"><a class="nav-link text-info" href="{% url 'Home:logout' %}">Logout</a></li>
                
                {% else %}
                    <li class="nav-item"><a class="nav-link " href="{% url 'Home:about' %}">Sobre nosotros</a></li>
                    <li class="nav-item"><a class="nav-link text-info" href="{% url 'Home:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/apps/Home/templates/Home/register.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
Registro de usuario
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-3"> 
            <button type="submit" class="btn btn-success">Registrar nuevo usuario</button>
        </div>
    </form>

{% endblock INDEX_CONTENIDO %}