project/apps/Seguros/urls.py
from django.urls import path

from . import views

app_name = "Seguros"

urlpatterns = [path("", views.index, name="home")]

# SEGUROCATEGORIA
urlpatterns += [
    path("seguroscategoria/list/", views.SegurosCategoriaList.as_view(), name="seguroscategoria_list"),
    path("seguroscategoria/create/", views.SegurosCategoriaCreate.as_view(), name="seguroscategoria_create"),
    path("seguroscategoria/detail/<int:pk>", views.SegurosCategoriaDetail.as_view(), name="seguroscategoria_detail"),
    path("seguroscategoria/update/<int:pk>", views.SegurosCategoriaUpdate.as_view(), name="seguroscategoria_update"),
    path("seguroscategoria/delete/<int:pk>", views.SegurosCategoriaDelete.as_view(), name="seguroscategoria_delete"),
]

# SEGURO
urlpatterns += [
    path("seguros/list/", views.SegurosList.as_view(), name="seguros_list"),
    path("seguros/create/", views.SegurosCreate.as_view(), name="seguros_create"),
    path("seguros/detail/<int:pk>", views.SegurosDetail.as_view(), name="seguros_detail"),
    path("seguros/update/<int:pk>", views.SegurosUpdate.as_view(), name="seguros_update"),
    path("seguros/delete/<int:pk>", views.SegurosDelete.as_view(), name="seguros_delete"),
]

project/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls")),
    path("Clientes/", include("Clientes.urls")),
    path("Seguros/", include("Seguros.urls")),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/Seguros/models.py
from django.db import models
from django.utils import timezone


class SegurosCategoria(models.Model):
    riesgo = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(
    max_length=250, null=True, blank=True, verbose_name="descripción")

    def __str__(self):
        return self.riesgo

    class Meta:
        verbose_name = "categoría de seguros"
        verbose_name_plural = "categorías de seguros"


class Seguros(models.Model):
    #Tipos de seguros
    riesgo = models.ForeignKey(SegurosCategoria, on_delete=models.SET_NULL, blank=True, null=True)
    seccion = models.CharField(max_length=250, null=True, blank=True)
    suma = models.FloatField()
    descripcion = models.CharField(max_length=250, null=True, blank=True)
    fecha_suscripcion = models.DateTimeField(default=timezone.now, editable=False, verbose_name="fecha de suscripcion")
    fotos = models.ImageField(upload_to= "fotos_inspeccion", blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.riesgo} {self.seccion} {self.descripcion}"

project/apps/Seguros/forms.py
from django import forms
from . import models


class SegurosCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.SegurosCategoria
        fields = "__all__"


class SegurosForm(forms.ModelForm):
    class Meta:
        model = models.Seguros
        fields = "__all__"

project/apps/Seguros/views.py
from typing import Any
from django.contrib.auth.decorators import login_required

# importaciones para login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models

# PAGINA PRINCIPAL


@login_required
def index(request):
    return render(request, "seguros/index.html")

class SegurosCategoriaList(ListView):
    model = models.SegurosCategoria


class SegurosCategoriaCreate(CreateView):
    model = models.SegurosCategoria
    form_class = forms.SegurosCategoriaForm
    success_url = reverse_lazy("Seguros:seguroscategoria_list")


class SegurosCategoriaDetail(DetailView):
    model = models.SegurosCategoria


class SegurosCategoriaUpdate(UpdateView):
    model = models.SegurosCategoria
    form_class = forms.SegurosCategoriaForm
    success_url = reverse_lazy("Seguros:seguroscategoria_list")


class SegurosCategoriaDelete(DeleteView):
    model = models.SegurosCategoria
    success_url = reverse_lazy("Seguros:seguroscategoria_list")


class SegurosList(ListView):
    model = models.Seguros

    def get_queryset(self) -> QuerySet[Any]:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Seguros.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Seguros.objects.all()
        return object_list


class SegurosCreate(CreateView):
    model = models.Seguros
    form_class = forms.SegurosForm
    success_url = reverse_lazy("Seguros:seguros_list")


class SegurosDetail(DetailView):
    model = models.Seguros


class SegurosUpdate(UpdateView):
    model = models.Seguros
    form_class = forms.SegurosForm
    success_url = reverse_lazy("Seguros:seguros_list")


class SegurosDelete(DeleteView):
    model = models.Seguros
    success_url = reverse_lazy("Seguros:seguros_list")

project/apps/Seguros/templates/seguros/index.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %} 
    Seguros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    
    <h3 class="pb-lg-3 ">
        Seguros
    </h3>
    
    <div class="d-grid gap-3 ">  
        
            <a href="{% url 'Seguros:seguros_create' %}" class="btn btn-primary ">Emitir Seguro</a>
            <br>
        
        <a href="{% url 'Seguros:seguros_list' %}" class="btn btn-primary ">Lista de seguros</a>
        <br>
    </div>

    {% include 'Home/index_back.html' %}

{% endblock INDEX_CONTENIDO %}

project/apps/Seguros/templates/seguros/seguros_confirm_delete.html
{% extends 'seguros/index.html' %}

{% block INDEX_TITULO %} 
    Cancelación de seguros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}

    <p class="fs-5 fst-italic">¿Confirma cancelar "{{ object }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>

    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Seguros/templates/seguros/seguros_detail.html
{% extends 'seguros/index.html' %}

{% block INDEX_TITULO %} 
    Detalle de Seguros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <ul>
        <li>Riesgo: {{ object.riesgo }} </li>
        <li>Sección: {{ object.seccion }} </li>
        <li>Suma Asegurada: {{ object.suma }} </li>
        <li>Descripción: {{ object.descripcion }} </li>
        <li>Fecha de suscripcion: {{ object.fecha_suscripcion }} </li>
        {% if object.fotos %}
            <li>Foto Inspección: <img src="{{ object.fotos.url }}" alt="Foto de inspección"></li>
        {% else %}
            <li>No hay foto de inspección disponible.</li>
        {% endif %}
    </ul>

    {% include 'Home/index_back.html' %}
    
{% endblock INDEX_CONTENIDO %}

project/apps/Seguros/templates/seguros/seguros_form.html
{% extends 'seguros/index.html' %}

{% block INDEX_TITULO %} 
    Crear/Actualizar Seguro
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Guardar</button>
    </form>
    
    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}

project/apps/Seguros/templates/seguros/seguros_list.html
{% extends 'seguros/index.html' %}

{% block INDEX_TITULO %} 
    Lista de Seguros
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    {% if object_list %}

        <div class="py-lg-4">
            <form action="{% url 'Seguros:seguros_list' %}" method="get">
                <input type="text" name="consulta" placeholder="Buscar">
            </form>
        </div>

        {% for object in object_list %}
            <ul>
                <li>{{ object.seccion }} ${{ object.suma }}
                    <a href="{% url 'Seguros:seguros_detail' object.id %}" class="btn btn-secondary btn-sm">
                        Ver detalle</a>
                    <a href="{% url 'Seguros:seguros_update' object.id %}" class="btn btn-primary  btn-sm">
                        Actualizar</a>
                    <a href="{% url 'Seguros:seguros_delete' object.id %}" class="btn btn-danger  btn-sm">
                        Eliminar</a>
                </li>
            </ul>
        {% endfor %}        
    {% else %}
        <p class="fs-4 fst-italic ">No hay registros ingresados</p>
    {% endif %}


    {% include 'Home/index_back.html' %}
{% endblock INDEX_CONTENIDO %}